// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UTF-8 path for preserving raw path compatibility at the app-server API
 * boundary while Codex migrates to [`PathUri`].
 *
 * Supports storing arbitrary strings read from the API and converting to and
 * from [`PathUri`] using an explicitly selected native path convention.
 *
 * "Native" refers to the supplied [`PathConvention`], which may be foreign to
 * the operating system running this process. The inner string is private so
 * path-producing code must render through [`Self::from_path_uri`] rather than
 * accidentally applying the current host's path rules. Opaque fallback paths
 * are decoded using the supplied convention and converted to UTF-8 lossily at
 * this API boundary because the value is serialized as a JSON string.
 *
 * Deserialization accepts any UTF-8 string without interpreting or validating
 * it. That unrestricted construction path is intentionally available only to
 * serde: Codex-internal code cannot construct this type directly from a raw
 * `String` and is instead encouraged to convert through [`PathUri`] or
 * [`AbsolutePathBuf`]. Relative path text remains valid until an operation
 * such as [`Self::to_path_uri`] requires an absolute path.
 */
export type ApiPathString = string;
